# Generated by Django 2.1.5 on 2019-01-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_text',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
