# Generated by Django 2.1.5 on 2019-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0002_auto_20190118_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_text', models.CharField(max_length=200)),
            ],
        ),
    ]
