# Generated by Django 2.1.5 on 2019-02-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0006_auto_20190201_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='extraanswer',
            old_name='extra_question_id',
            new_name='extra_question',
        ),
    ]
